server:
  #服务端口
  port: 9006
spring:
  application:
    #指定服务名
    name: tensquare-spit
  #数据源配置
  data:
    mongodb:
      # 主机地址
      host: 192.168.61.131
      # 数据库
      database: spitdb
      # 默认端口是27017
      port: 27017
  redis:
    # Redis服务器地址（默认localhost）
    host: 192.168.61.131
    # Redis服务器连接端口（6379）
    port: 6379
    # Redis数据库索引（默认为0）
    #      database: 0
    #      # Redis服务器连接密码（默认为空）
    #      password:
    # 连接超时时间（毫秒）
    timeout: 5000
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制，默认是8）
        max-active: 8
        # 连接池中的最大空闲连接（使用负值表示没有限制，默认是8）
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制，默认是-1ms）
        max-wait: -1ms
        # 连接池中的最小空闲连接（默认是0）
        min-idle: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true